name: Go Short Test
on: [push]
jobs:
  quicktest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Install RunRevive Linter
        run: go install -v github.com/mgechev/revive@latest
      - name: Run Revive Linter
        run: revive -formatter friendly -config revive.toml ./...
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run staticcheck
        run: staticcheck ./pkg/...
      - name: Run tests
        run: go test -v ./pkg/...